
CLASS ltcl_add DEFINITION FOR TESTING DURATION SHORT RISK LEVEL HARMLESS FINAL.

  PRIVATE SECTION.
    METHODS: add1 FOR TESTING,
      add2 FOR TESTING.

ENDCLASS.       "ltcl_Add

CLASS ltcl_add IMPLEMENTATION.

  METHOD add1.

  ENDMETHOD.

  METHOD add2.

  ENDMETHOD.

ENDCLASS.